server:
  port: 8500
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8700/eureka/
spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fuckaway/master/tree/master
          username: 572194344@qq.com
          password: fu120105123313
